-- return {
--   "kkoomen/vim-doge",
--   config = function()
--     -- vim.g.doge_doc_standard_python = ""
--     vim.api.nvim_command("filetype plugin indent on")
--     vim.cmd("call doge#install()")
--   end,
--   keys = {
--     -- { "<leader>cD", "<cmd>DogeGenerate<cr>", desc = "Generate Docstring" },
--   },
-- }
